# Generated by Django 4.1.7 on 2023-03-30 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('contract_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='files_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_upload', to='assureplus_back.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='assureplus_back.users')),
            ],
        ),
    ]
