# Generated by Django 4.1.7 on 2023-04-02 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assureplus_back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistres',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sinistre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='files_upload',
            name='sinistre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_upload', to='assureplus_back.sinistres'),
        ),
        migrations.AddField(
            model_name='comments',
            name='sinistre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='assureplus_back.sinistres'),
        ),
    ]
