# Generated by Django 4.1.7 on 2023-03-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assureplus_back', '0002_remove_comments_users_remove_files_upload_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contract_number',
            field=models.IntegerField(unique=True),
        ),
    ]
