# Generated by Django 4.1.7 on 2023-03-30 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assureplus_back', '0003_alter_users_contract_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='sinitres',
        ),
        migrations.RemoveField(
            model_name='files_upload',
            name='sinitres',
        ),
        migrations.RemoveField(
            model_name='sinitres',
            name='users',
        ),
        migrations.AddField(
            model_name='comments',
            name='sinitre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='assureplus_back.sinitres'),
        ),
        migrations.AddField(
            model_name='files_upload',
            name='sinitre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_upload', to='assureplus_back.sinitres'),
        ),
        migrations.AddField(
            model_name='sinitres',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sinitres', to='assureplus_back.users'),
        ),
    ]
