# Generated by Django 4.1.7 on 2023-03-31 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assureplus_back', '0004_remove_comments_sinitres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinitres',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sinitres',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sinitre', to='assureplus_back.users'),
        ),
    ]
