# Generated by Django 4.1.7 on 2023-03-31 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assureplus_back', '0005_sinitres_date_users_date_alter_comments_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='date',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='sinitres',
            old_name='date',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='date',
            new_name='date_time',
        ),
    ]
