# Generated by Django 4.1.7 on 2023-03-31 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assureplus_back', '0006_rename_date_comments_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
