# Generated by Django 4.1.7 on 2023-03-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assureplus_back', '0007_alter_users_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
