# Generated by Django 4.1.7 on 2023-03-31 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assureplus_back', '0008_users_email_users_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
    ]
