# Generated by Django 4.1.7 on 2023-04-01 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assureplus_back', '0009_remove_users_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinistres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sinistre', to='assureplus_back.users')),
            ],
        ),
        migrations.RemoveField(
            model_name='comments',
            name='sinitre',
        ),
        migrations.RemoveField(
            model_name='files_upload',
            name='sinitre',
        ),
        migrations.DeleteModel(
            name='Sinitres',
        ),
        migrations.AddField(
            model_name='comments',
            name='sinistre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='assureplus_back.sinistres'),
        ),
        migrations.AddField(
            model_name='files_upload',
            name='sinistre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_upload', to='assureplus_back.sinistres'),
        ),
    ]
