# Generated by Django 4.1.7 on 2023-04-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assureplus_back', '0012_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='street',
            field=models.CharField(max_length=100),
        ),
    ]
