# Generated by Django 4.1.7 on 2023-04-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_users_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
