# Generated by Django 4.1.7 on 2023-04-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_alter_users_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
